name: Sync to Production

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Skip .github/workflows Files
        run: |
          git ls-files -z .github/workflows/ | xargs -0 git update-index --skip-worktree

      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Verify SSH Key Loaded
        run: ssh-add -L

      - name: Add Production Remote and Push Changes
        run: |
          git remote add production git@github.com:hasun-retool/nbcGithubProduction.git
          # Optional: show current remotes for debugging
          git remote -v
          git push production main --force
