name: Sync to Production

on:
  push:
    branches:
      - main  # Adjust if your primary branch has a different name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add Production Remote via SSH
        run: |
          git remote add production git@github.com:hasun-retool/nbcGithubProduction.git

      - name: Push to Production
        run: |
          git push production main --force
