name: Sync to Production

on:
  push:
    branches:
      - main  # Adjust if your primary branch has a different name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire history

      - name: Set up SSH
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf '%b' "$DEPLOY_SSH_KEY" > ~/.ssh/sync_deploy_rsa
          chmod 600 ~/.ssh/sync_deploy_rsa
          # Start the SSH agent and capture its environment variables in the same shell session
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/sync_deploy_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add -L  # Debug: list loaded keys
          
      - name: List loaded SSH keys
        run: |
          ssh-add -L || echo "No keys loaded"

      - name: Add Production Remote via SSH
        run: |
          git remote add production git@github.com:hasun-retool/nbcGithubProduction.git

      - name: Push to Production
        run: |
          git push production main --force
